[2024-03-18T23:20:34.634+0000] {logging_mixin.py:154} INFO - Changing /opt/***/logs/dag_id=recalls_etl_v1/run_id=manual__2024-03-18T23:20:32.494549+00:00/task_id=get_raw_data permission to 509
[2024-03-18T23:20:34.667+0000] {logging_mixin.py:154} INFO - Changing /opt/***/logs/dag_id=recalls_etl_v1/run_id=manual__2024-03-18T23:20:32.494549+00:00/task_id=get_raw_data permission to 509
[2024-03-18T23:20:34.710+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: recalls_etl_v1.get_raw_data manual__2024-03-18T23:20:32.494549+00:00 [queued]>
[2024-03-18T23:20:34.720+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: recalls_etl_v1.get_raw_data manual__2024-03-18T23:20:32.494549+00:00 [queued]>
[2024-03-18T23:20:34.720+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2024-03-18T23:20:34.738+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): get_raw_data> on 2024-03-18 23:20:32.494549+00:00
[2024-03-18T23:20:34.743+0000] {standard_task_runner.py:57} INFO - Started process 2376 to run task
[2024-03-18T23:20:34.746+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'recalls_etl_v1', 'get_raw_data', 'manual__2024-03-18T23:20:32.494549+00:00', '--job-id', '42', '--raw', '--subdir', 'DAGS_FOLDER/recalls_etl_v1.py', '--cfg-path', '/tmp/tmpuyqw54ln']
[2024-03-18T23:20:34.748+0000] {standard_task_runner.py:85} INFO - Job 42: Subtask get_raw_data
[2024-03-18T23:20:34.804+0000] {logging_mixin.py:154} INFO - Changing /opt/***/logs/dag_id=recalls_etl_v1/run_id=manual__2024-03-18T23:20:32.494549+00:00/task_id=get_raw_data permission to 509
[2024-03-18T23:20:34.810+0000] {task_command.py:416} INFO - Running <TaskInstance: recalls_etl_v1.get_raw_data manual__2024-03-18T23:20:32.494549+00:00 [running]> on host 3694d3cee1cf
[2024-03-18T23:20:34.899+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='recalls_etl_v1' AIRFLOW_CTX_TASK_ID='get_raw_data' AIRFLOW_CTX_EXECUTION_DATE='2024-03-18T23:20:32.494549+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-03-18T23:20:32.494549+00:00'
[2024-03-18T23:20:38.057+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 2488659 (char 2488658)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/recalls_etl_v1.py", line 43, in get_recall_data
    response_data = response.json()
  File "/home/airflow/.local/lib/python3.8/site-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 2488659 (char 2488658)
[2024-03-18T23:20:38.076+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=recalls_etl_v1, task_id=get_raw_data, execution_date=20240318T232032, start_date=20240318T232034, end_date=20240318T232038
[2024-03-18T23:20:38.093+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 42 for task get_raw_data (Expecting value: line 1 column 2488659 (char 2488658); 2376)
[2024-03-18T23:20:38.133+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-03-18T23:20:38.170+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
