[2024-03-18T22:31:44.139+0000] {logging_mixin.py:154} INFO - Changing /opt/***/logs/dag_id=recalls_etl_v1/run_id=manual__2024-03-18T22:31:38.824710+00:00/task_id=clean_raw_data permission to 509
[2024-03-18T22:31:44.168+0000] {logging_mixin.py:154} INFO - Changing /opt/***/logs/dag_id=recalls_etl_v1/run_id=manual__2024-03-18T22:31:38.824710+00:00/task_id=clean_raw_data permission to 509
[2024-03-18T22:31:44.201+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: recalls_etl_v1.clean_raw_data manual__2024-03-18T22:31:38.824710+00:00 [queued]>
[2024-03-18T22:31:44.211+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: recalls_etl_v1.clean_raw_data manual__2024-03-18T22:31:38.824710+00:00 [queued]>
[2024-03-18T22:31:44.212+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2024-03-18T22:31:44.227+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): clean_raw_data> on 2024-03-18 22:31:38.824710+00:00
[2024-03-18T22:31:44.232+0000] {standard_task_runner.py:57} INFO - Started process 1584 to run task
[2024-03-18T22:31:44.235+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'recalls_etl_v1', 'clean_raw_data', 'manual__2024-03-18T22:31:38.824710+00:00', '--job-id', '26', '--raw', '--subdir', 'DAGS_FOLDER/recalls_etl_v1.py', '--cfg-path', '/tmp/tmpnz57dmh3']
[2024-03-18T22:31:44.237+0000] {standard_task_runner.py:85} INFO - Job 26: Subtask clean_raw_data
[2024-03-18T22:31:44.283+0000] {logging_mixin.py:154} INFO - Changing /opt/***/logs/dag_id=recalls_etl_v1/run_id=manual__2024-03-18T22:31:38.824710+00:00/task_id=clean_raw_data permission to 509
[2024-03-18T22:31:44.291+0000] {task_command.py:416} INFO - Running <TaskInstance: recalls_etl_v1.clean_raw_data manual__2024-03-18T22:31:38.824710+00:00 [running]> on host 3694d3cee1cf
[2024-03-18T22:31:44.369+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='recalls_etl_v1' AIRFLOW_CTX_TASK_ID='clean_raw_data' AIRFLOW_CTX_EXECUTION_DATE='2024-03-18T22:31:38.824710+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-03-18T22:31:38.824710+00:00'
[2024-03-18T22:31:44.374+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/recalls_etl_v1.py", line 78, in clean_recall_data
    df = pd.read_csv(raw_input_path)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 912, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 577, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 1407, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 1661, in _make_engine
    self.handles = get_handle(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/common.py", line 859, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/data/raw/recalls_raw.csv'
[2024-03-18T22:31:44.392+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=recalls_etl_v1, task_id=clean_raw_data, execution_date=20240318T223138, start_date=20240318T223144, end_date=20240318T223144
[2024-03-18T22:31:44.406+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 26 for task clean_raw_data ([Errno 2] No such file or directory: '/opt/airflow/data/raw/recalls_raw.csv'; 1584)
[2024-03-18T22:31:44.449+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-03-18T22:31:44.473+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
