[2024-03-18T22:31:41.749+0000] {logging_mixin.py:154} INFO - Changing /opt/***/logs/dag_id=recalls_etl_v1/run_id=manual__2024-03-18T22:31:38.824710+00:00/task_id=get_raw_data permission to 509
[2024-03-18T22:31:41.788+0000] {logging_mixin.py:154} INFO - Changing /opt/***/logs/dag_id=recalls_etl_v1/run_id=manual__2024-03-18T22:31:38.824710+00:00/task_id=get_raw_data permission to 509
[2024-03-18T22:31:41.833+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: recalls_etl_v1.get_raw_data manual__2024-03-18T22:31:38.824710+00:00 [queued]>
[2024-03-18T22:31:41.842+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: recalls_etl_v1.get_raw_data manual__2024-03-18T22:31:38.824710+00:00 [queued]>
[2024-03-18T22:31:41.842+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2024-03-18T22:31:41.863+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): get_raw_data> on 2024-03-18 22:31:38.824710+00:00
[2024-03-18T22:31:41.869+0000] {standard_task_runner.py:57} INFO - Started process 1581 to run task
[2024-03-18T22:31:41.874+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'recalls_etl_v1', 'get_raw_data', 'manual__2024-03-18T22:31:38.824710+00:00', '--job-id', '25', '--raw', '--subdir', 'DAGS_FOLDER/recalls_etl_v1.py', '--cfg-path', '/tmp/tmpy8j9lrkr']
[2024-03-18T22:31:41.876+0000] {standard_task_runner.py:85} INFO - Job 25: Subtask get_raw_data
[2024-03-18T22:31:41.934+0000] {logging_mixin.py:154} INFO - Changing /opt/***/logs/dag_id=recalls_etl_v1/run_id=manual__2024-03-18T22:31:38.824710+00:00/task_id=get_raw_data permission to 509
[2024-03-18T22:31:41.943+0000] {task_command.py:416} INFO - Running <TaskInstance: recalls_etl_v1.get_raw_data manual__2024-03-18T22:31:38.824710+00:00 [running]> on host 3694d3cee1cf
[2024-03-18T22:31:42.035+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='recalls_etl_v1' AIRFLOW_CTX_TASK_ID='get_raw_data' AIRFLOW_CTX_EXECUTION_DATE='2024-03-18T22:31:38.824710+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-03-18T22:31:38.824710+00:00'
[2024-03-18T22:31:42.092+0000] {warnings.py:109} WARNING - /opt/***/dags/recalls_etl_v1.py:74: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  recalls_df.rename(columns={'NID': 'recall_id', 'Organization': 'organization','Product':'product_name','Issue':'issue','Category':'category','Last updated':'updated_at'}, inplace=True)

[2024-03-18T22:31:42.094+0000] {python.py:194} INFO - Done. Returned value was: None
[2024-03-18T22:31:42.111+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=recalls_etl_v1, task_id=get_raw_data, execution_date=20240318T223138, start_date=20240318T223141, end_date=20240318T223142
[2024-03-18T22:31:42.166+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2024-03-18T22:31:42.198+0000] {taskinstance.py:2778} INFO - 1 downstream tasks scheduled from follow-on schedule check
