[2024-03-13T01:50:20.399+0000] {logging_mixin.py:154} INFO - Changing /opt/***/logs/dag_id=recalls_etl_v1/run_id=manual__2024-03-13T01:50:18.872816+00:00/task_id=get_raw_data permission to 509
[2024-03-13T01:50:20.432+0000] {logging_mixin.py:154} INFO - Changing /opt/***/logs/dag_id=recalls_etl_v1/run_id=manual__2024-03-13T01:50:18.872816+00:00/task_id=get_raw_data permission to 509
[2024-03-13T01:50:20.464+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: recalls_etl_v1.get_raw_data manual__2024-03-13T01:50:18.872816+00:00 [queued]>
[2024-03-13T01:50:20.472+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: recalls_etl_v1.get_raw_data manual__2024-03-13T01:50:18.872816+00:00 [queued]>
[2024-03-13T01:50:20.472+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2024-03-13T01:50:20.487+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): get_raw_data> on 2024-03-13 01:50:18.872816+00:00
[2024-03-13T01:50:20.492+0000] {standard_task_runner.py:57} INFO - Started process 1242 to run task
[2024-03-13T01:50:20.495+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'recalls_etl_v1', 'get_raw_data', 'manual__2024-03-13T01:50:18.872816+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/recalls_etl_v1.py', '--cfg-path', '/tmp/tmpm5spnnta']
[2024-03-13T01:50:20.496+0000] {standard_task_runner.py:85} INFO - Job 5: Subtask get_raw_data
[2024-03-13T01:50:20.540+0000] {logging_mixin.py:154} INFO - Changing /opt/***/logs/dag_id=recalls_etl_v1/run_id=manual__2024-03-13T01:50:18.872816+00:00/task_id=get_raw_data permission to 509
[2024-03-13T01:50:20.548+0000] {task_command.py:416} INFO - Running <TaskInstance: recalls_etl_v1.get_raw_data manual__2024-03-13T01:50:18.872816+00:00 [running]> on host 3694d3cee1cf
[2024-03-13T01:50:20.616+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='recalls_etl_v1' AIRFLOW_CTX_TASK_ID='get_raw_data' AIRFLOW_CTX_EXECUTION_DATE='2024-03-13T01:50:18.872816+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-03-13T01:50:18.872816+00:00'
[2024-03-13T01:50:23.487+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.8/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Unterminated string starting at: line 1 column 2149645 (char 2149644)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/recalls_etl_v1.py", line 39, in get_recall_data
    response_data = json.loads(response.json())
  File "/home/airflow/.local/lib/python3.8/site-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Unterminated string starting at: line 1 column 2149645 (char 2149644)
[2024-03-13T01:50:23.501+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=recalls_etl_v1, task_id=get_raw_data, execution_date=20240313T015018, start_date=20240313T015020, end_date=20240313T015023
[2024-03-13T01:50:23.514+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 5 for task get_raw_data (Unterminated string starting at: line 1 column 2149645 (char 2149644); 1242)
[2024-03-13T01:50:23.559+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-03-13T01:50:23.584+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
